//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Chap8.MVP.UI.Web.Home {
    
    
    public partial class Index {
        
        /// <summary>
        /// plBestSellingProducts control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Chap8.MVP.UI.Web.Shared.ProductList plBestSellingProducts;
    }
}
